/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package barbarloan.layout;

import barbarloan.connection.ConnectionDB;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author Ansori San
 */
public class DashboardEmployee extends javax.swing.JFrame {

    /**
     * Creates new form DashboardAdmin
     */
    public DashboardEmployee(String username) {
        initComponents(username);
        this.showTable(reqTable,username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(String username) {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        reqTable = new javax.swing.JTable();
        tvRequest = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuBorrow = new javax.swing.JMenu();
        borrow = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Employee Dashboard");

        reqTable.setFont(new java.awt.Font("Product Sans", 0, 12)); // NOI18N
        reqTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "#", "Employee Name", "Tools", "Quantity", "Status", "Borrow Date", "Duration", "aidi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(reqTable);

        tvRequest.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        tvRequest.setForeground(java.awt.Color.white);
        tvRequest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tvRequest.setText("Request");
        tvRequest.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        Logout.setBackground(java.awt.Color.white);
        Logout.setFont(new java.awt.Font("Product Sans", 1, 12)); // NOI18N
        Logout.setForeground(new java.awt.Color(33, 150, 243));
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(tvRequest, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Logout, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Logout))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tvRequest, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logout)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tvRequest)
                    .addContainerGap(403, Short.MAX_VALUE)))
        );

        jMenuBar2.setFont(new java.awt.Font("Product Sans", 0, 12)); // NOI18N

        menuBorrow.setText("Borrow");
        menuBorrow.setFont(new java.awt.Font("Product Sans", 0, 12)); // NOI18N

        borrow.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        borrow.setText("Borrow Tools");
        borrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowActionPerformed(evt,username);
            }
        });
        menuBorrow.add(borrow);

        jMenuBar2.add(menuBorrow);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_LogoutActionPerformed

    private void borrowActionPerformed(java.awt.event.ActionEvent evt, String username) {//GEN-FIRST:event_borrowActionPerformed
        BorrowTools borrowTools = new BorrowTools(username);
        jDesktopPane1.add(borrowTools);
        borrowTools.setVisible(true);
    }//GEN-LAST:event_borrowActionPerformed

    public void showTable(JTable table, String username) {
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("#");
        tableModel.addColumn("Employee Name");
        tableModel.addColumn("Tool");
        tableModel.addColumn("Quantity");
        tableModel.addColumn("Status");
        tableModel.addColumn("Borrow Date");
        tableModel.addColumn("Return Date");
        tableModel.addColumn("");


        try {
            Connection conn = ConnectionDB.conn();
            String sqlQuery = "select a.quantity, a.status, a.loan_date, a.return_date, b.name, c.name, d.username from request as a inner join detail_user as b on a.detailUser_id = b.id right join tool as c on a.tool_id - c.id right join user as d on b.user_id = d.id where d.username = '"+username+"'";
            Statement statement = conn.createStatement();
            ResultSet resultSet = statement.executeQuery(sqlQuery);
            int no = 0;

            while (resultSet.next()) {
                no++;
                tableModel.addRow(new Object[] {
                        no,
                        resultSet.getString(5),
                        resultSet.getString(6),
                        resultSet.getString(1),
                        resultSet.getString(2),
                        resultSet.getString(3),
                        resultSet.getString(4)
                });
            }

            table.setModel(tableModel);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.toString());
        }

        reqTable.removeColumn(reqTable.getColumnModel().getColumn(7));
    }

    public JTable getReqTable() {
        return reqTable;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JMenuItem borrow;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuBorrow;
    private javax.swing.JTable reqTable;
    private javax.swing.JLabel tvRequest;
    // End of variables declaration//GEN-END:variables
}
